<a href="https://colab.research.google.com/github/Abinayak03/Deep-learning/blob/main/7_1_nn_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 align="center">Codebasics DL Course: Employee Bonus Prediction</h2>

https://chatgpt.com/c/67dd06f0-7f84-8010-8c62-a2b1bbb41084

#### Load the Dataset

In [1]:
import pandas as pd

# Load data from CSV file
df = pd.read_csv("bonus.csv")
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

#### Train Test Split

In [2]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df[['performance', 'years_of_experience', 'projects_completed']].values
y = df[['bonus']].values  # Ensure target is a 2D array for compatibility

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#### Train a Neural Network

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# Seed for reproducibility
torch.manual_seed(0)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [4]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3, 1),  # 3 input features -> 1 output neuron
        )

    def forward(self, x):
        return self.network(x)

In [5]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.005)

In [6]:
# Training loop
epochs = 5000
for epoch in range(epochs):
    # Forward pass: Compute predicted bonus by passing X_train
    predictions = model(X_train_tensor)
    loss = criterion(predictions, y_train_tensor)

    # Backward pass: Compute gradients
    optimizer.zero_grad()
    loss.backward()

    # Update parameters
    optimizer.step()

    # Print loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.2f}")

Epoch [100/5000], Loss: 22.07
Epoch [200/5000], Loss: 19.01
Epoch [300/5000], Loss: 16.60
Epoch [400/5000], Loss: 14.56
Epoch [500/5000], Loss: 12.80
Epoch [600/5000], Loss: 11.27
Epoch [700/5000], Loss: 9.92
Epoch [800/5000], Loss: 8.73
Epoch [900/5000], Loss: 7.69
Epoch [1000/5000], Loss: 6.77
Epoch [1100/5000], Loss: 5.96
Epoch [1200/5000], Loss: 5.25
Epoch [1300/5000], Loss: 4.62
Epoch [1400/5000], Loss: 4.07
Epoch [1500/5000], Loss: 3.58
Epoch [1600/5000], Loss: 3.15
Epoch [1700/5000], Loss: 2.78
Epoch [1800/5000], Loss: 2.44
Epoch [1900/5000], Loss: 2.15
Epoch [2000/5000], Loss: 1.90
Epoch [2100/5000], Loss: 1.67
Epoch [2200/5000], Loss: 1.47
Epoch [2300/5000], Loss: 1.29
Epoch [2400/5000], Loss: 1.14
Epoch [2500/5000], Loss: 1.00
Epoch [2600/5000], Loss: 0.88
Epoch [2700/5000], Loss: 0.78
Epoch [2800/5000], Loss: 0.68
Epoch [2900/5000], Loss: 0.60
Epoch [3000/5000], Loss: 0.53
Epoch [3100/5000], Loss: 0.47
Epoch [3200/5000], Loss: 0.41
Epoch [3300/5000], Loss: 0.36
Epoch [3400/5

In [7]:
# Switch to evaluation mode (important for models with dropout/batch norm layers)
model.eval()

# Disable gradient calculations for evaluation to save memory
with torch.no_grad():
    test_predictions = model(X_test_tensor)
    test_loss = criterion(test_predictions, y_test_tensor)

print(f"Test Loss: {test_loss.item():.4f}")

Test Loss: 0.0417


In [8]:
X_test_tensor[:3]

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [9]:
test_predictions[:3]

tensor([[189.9579],
        [150.1561],
        [113.7303]])

In [10]:
y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [11]:
for name, value in model.named_parameters():
    print(f"Name: {name}, Value: {value}")

Name: network.0.weight, Value: Parameter containing:
tensor([[12.0335,  5.8423,  2.1879]], requires_grad=True)
Name: network.0.bias, Value: Parameter containing:
tensor([19.2311], requires_grad=True)
