<a href="https://colab.research.google.com/github/Abinayak03/Deep-learning/blob/main/Activation_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**ACTIVATION FUNCTION**

*sigmoid*

In [2]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

values=np.array([-2,-1,0,1,2,50,600,56])
sigmoid(values)

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708,
       1.        , 1.        , 1.        ])

*softmax*

In [5]:
def softmax(x):
  exp_x=np.exp(x-np.max(x))
  return exp_x/exp_x.sum(axis=0)

values=np.array([3,8,9,7,4])
softmax(values)

array([0.00163892, 0.24323711, 0.661187  , 0.08948193, 0.00445504])

*tanh*

In [6]:
def tanh(x):
  return np.tanh(x)

values=np.array([-2,-1,0,1,2,50,600,56])
tanh(values)

array([-0.96402758, -0.76159416,  0.        ,  0.76159416,  0.96402758,
        1.        ,  1.        ,  1.        ])

*ReLU*

In [7]:
def relu(x):
  return np.maximum(0,x)

values=np.array([-2,-1,0,1,2,50,600,56])
relu(values)

array([  0,   0,   0,   1,   2,  50, 600,  56])