<a href="https://colab.research.google.com/github/Abinayak03/Deep-learning/blob/main/pytorch_basics_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [7]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cuda




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [12]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]
inventory=torch.tensor(inventory,dtype=torch.float32)

In [13]:
torch.is_tensor(inventory)

True

In [15]:
#2 Find the total inventory for each item across all days
inventory.sum(dim=0)

tensor([42., 33., 32., 10., 11.])

In [16]:
#3 Find the average inventory per day
inventory.mean(dim=1)

tensor([ 8.4000,  6.8000, 10.4000])



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [19]:
#1 Simulate this data using PyTorch's Random Functions
road1=torch.randint(50,200,(1,24))
road2=torch.randint(50,200,(1,24))
road1,road2

(tensor([[184,  93,  85, 155, 163, 116,  91, 167, 128,  95,  84,  90,  67,  65,
          136, 134, 144, 143, 198,  65, 179, 143, 115, 160]]),
 tensor([[199, 101, 138,  64, 124,  78, 170, 164, 104,  64, 180, 159, 115, 101,
          126, 107, 104, 159, 186,  78,  54, 116,  63, 180]]))

In [20]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
def total_vehicle_flow():
  return road1.sum(),road2.sum()
total_vehicle_flow()

(tensor(3000), tensor(2934))

In [22]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
def total_vehicle_flow_per_hour():
  return road1+road2
total_vehicle_flow_per_hour()

tensor([[383, 194, 223, 219, 287, 194, 261, 331, 232, 159, 264, 249, 182, 166,
         262, 241, 248, 302, 384, 143, 233, 259, 178, 340]])



---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [27]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
gym=torch.randint(50,100,(3,3))
print(gym)
weight_factor=torch.tensor([0.8,1.2,1.5])
scores_f=gym*weight_factor
scores_f

tensor([[91, 89, 97],
        [72, 88, 84],
        [82, 50, 74]])


tensor([[ 72.8000, 106.8000, 145.5000],
        [ 57.6000, 105.6000, 126.0000],
        [ 65.6000,  60.0000, 111.0000]])

In [28]:
#2 Find the row-wise and column-wise maximum scores
print(scores_f.max(dim=0))
print(scores_f.max(dim=1))

torch.return_types.max(
values=tensor([ 72.8000, 106.8000, 145.5000]),
indices=tensor([0, 0, 0]))
torch.return_types.max(
values=tensor([145.5000, 126.0000, 111.0000]),
indices=tensor([2, 2, 2]))


In [30]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
transpose_scores_f=scores_f.T
transpose_scores_f

tensor([[ 72.8000,  57.6000,  65.6000],
        [106.8000, 105.6000,  60.0000],
        [145.5000, 126.0000, 111.0000]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [38]:
#1 Use PyTorch to compute 'y' for x = 4
# let's define x first
x = torch.tensor(4.0, requires_grad=True , dtype=torch.float32)

# now define y
y = 2*x**3 + 5*x**2 - 3*x + 7

print(y)


tensor(203., grad_fn=<AddBackward0>)


In [39]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward()
gradient=x.grad
print(gradient)

tensor(133.)




---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [40]:

camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])


In [41]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)

camera1*camera2

tensor([[ 5, 12],
        [21, 32]])

In [42]:
#2 Compute Dot Product of the two matrices
torch.matmul(camera1,camera2)

tensor([[19, 22],
        [43, 50]])

In [45]:
#3 Compute the Determinant of each matrix
torch.det(camera1.float()),torch.det(camera2.float())

(tensor(-2.), tensor(-2.0000))



---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [46]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]
w=torch.tensor(2.0)
b=torch.tensor(1.0)
x=torch.tensor([1,2,3,4])

In [48]:
#2 Compute tensors for y
y=w*x+b
y

tensor([3., 5., 7., 9.])



---

