<a href="https://colab.research.google.com/github/Abinayak03/Deep-learning/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
print(torch.cuda.is_available())

True


In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


Using device: cuda


In [4]:
revenue=torch.tensor([100,120,300,33,334])

In [5]:
revenue[:3]

tensor([100, 120, 300])

In [6]:
q1=torch.tensor([
    [200,220,250],
    [150,180,210],
    [300,330,360]
])
q2=torch.tensor([
    [209,231,259],
    [155,192,222],
    [310,340,375]
])

In [7]:
q1+q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [8]:
0.1*q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [9]:
#elementwise multiplication
q1*q2

tensor([[ 41800,  50820,  64750],
        [ 23250,  34560,  46620],
        [ 93000, 112200, 135000]])

In [10]:
#matrix multiplication
torch.matmul(q1,q2)

tensor([[153400, 173440, 194390],
        [124350, 140610, 157560],
        [225450, 255060, 285960]])

In [11]:
#transpose
q1.t()

tensor([[200, 150, 300],
        [220, 180, 330],
        [250, 210, 360]])

In [12]:
q1.sum(dim=1)

tensor([670, 540, 990])

In [13]:
if torch.cuda.is_available():
  device=torch.device("cuda")
else:
  device=torch.device("cpu")
print(f"Using device: {device}")

Using device: cuda


In [14]:
# simulating customer data with 1 million customers and 3 features (age,spendig score, income)
customer_data=torch.rand(1_000_000,3,device=device)
customer_data.shape

torch.Size([1000000, 3])

In [15]:
customer_data[:5]

tensor([[0.8235, 0.5224, 0.4688],
        [0.6206, 0.0045, 0.7932],
        [0.6194, 0.9265, 0.5861],
        [0.5543, 0.9746, 0.3803],
        [0.4386, 0.9115, 0.7184]], device='cuda:0')

In [16]:
customer_data[:,1]

tensor([0.5224, 0.0045, 0.9265,  ..., 0.3019, 0.8631, 0.6199], device='cuda:0')

In [17]:
high_spending=customer_data[customer_data[:,1]>0.5]
high_spending

tensor([[0.8235, 0.5224, 0.4688],
        [0.6194, 0.9265, 0.5861],
        [0.5543, 0.9746, 0.3803],
        ...,
        [0.9547, 0.5953, 0.6247],
        [0.6216, 0.8631, 0.7117],
        [0.6072, 0.6199, 0.1888]], device='cuda:0')

In [18]:
high_spending.shape

torch.Size([500209, 3])

In [19]:
#to store data to cpu
high_spending.to("cpu")


tensor([[0.8235, 0.5224, 0.4688],
        [0.6194, 0.9265, 0.5861],
        [0.5543, 0.9746, 0.3803],
        ...,
        [0.9547, 0.5953, 0.6247],
        [0.6216, 0.8631, 0.7117],
        [0.6072, 0.6199, 0.1888]])

In [20]:
q1.dtype

torch.int64

In [21]:
#to reshape
q1.view(-1)

tensor([200, 220, 250, 150, 180, 210, 300, 330, 360])

In [22]:
units=torch.tensor([
    [23,34],
    [23,34],
    [45,56]
])

In [23]:
units.device

device(type='cpu')

In [24]:
units.view(2,3)

tensor([[23, 34, 23],
        [34, 45, 56]])

In [25]:
units[2,1]=90
units

tensor([[23, 34],
        [23, 34],
        [45, 90]])

In [26]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])